name: main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build {{ project_name }}
    strategy:
      matrix:
        python: [3.12]
    env:
      DATABASE_URL: "sqlite:///"
      REDIS_URL: "redis://"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Store branch and latest SHA
        id: git
        shell: bash
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Python ${% templatetag openvariable %} matrix.python {% templatetag closevariable %}
        uses: actions/setup-python@v5
        with:
          python-version: ${% templatetag openvariable %} matrix.python {% templatetag closevariable %}

      - name: Cache pip
        uses: actions/cache@v4
        env:
          cache_name: pip-cache
        with:
          path: ~/.cache/pip
          key: build-${% templatetag openvariable %} env.cache_name {% templatetag closevariable %}-${% templatetag openvariable %} steps.git.outputs.branch {% templatetag closevariable %}-${% templatetag openvariable %} steps.git.outputs.sha_short {% templatetag closevariable %}
          restore-keys: |
            build-${% templatetag openvariable %} env.cache_name {% templatetag closevariable %}-${% templatetag openvariable %} steps.git.outputs.branch {% templatetag closevariable %}
            build-${% templatetag openvariable %} env.cache_name {% templatetag closevariable %}

      - run: python -m pip install --upgrade pip
        shell: bash

      - run: python -m pip install poetry==2.0.1
        shell: bash

      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        shell: bash

      - run: sudo apt-get install git-lfs --upgrade
        shell: bash

      - name: Poetry install
        run: poetry install --with dev --no-root --no-interaction --no-ansi
        shell: bash

      - name: Generate secret key
        id: secret_id_generator
        shell: bash
        run: |
          secret=$(python -c "import uuid; print(uuid.uuid4().hex + uuid.uuid4().hex)")
          echo "SECRET_KEY=$secret" >> $GITHUB_OUTPUT

      - name: Linting
        run: poetry run ruff check ./
        env:
          DJANGO_SETTINGS_MODULE: "{{ project_name }}.settings.local_base"
          SECRET_KEY: ${% templatetag openvariable %} steps.secret_id_generator.outputs.SECRET_KEY {% templatetag closevariable %}
          DATABASE_URL: "sqlite:///"
          ALLOWED_HOSTS: ".example.org"
          SENDGRID_USERNAME: "test"
          SENDGRID_PASSWORD: "test"
          REDIS_URL: "redis://"
        shell: bash

      - run: poetry run pre-commit run --all-files
        env:
          SKIP: ruff,missing-migrations,backend-schema
        shell: bash

      - name: Check migrations (dry-run)
        run: |
          poetry run python manage.py makemigrations --check --dry-run
        env:
          DJANGO_SETTINGS_MODULE: "{{ project_name }}.settings.production"
          SECRET_KEY: ${% templatetag openvariable %} steps.secret_id_generator.outputs.SECRET_KEY {% templatetag closevariable %}
          DATABASE_URL: "sqlite:///"
          ALLOWED_HOSTS: ".example.org"
          SENDGRID_USERNAME: "test"
          SENDGRID_PASSWORD: "test"
          REDIS_URL: "redis://"
        shell: bash

      - name: Django deploy checks
        run: |
          poetry run python manage.py check --deploy
        env:
          DJANGO_SETTINGS_MODULE: "{{ project_name }}.settings.production"
          SECRET_KEY: ${% templatetag openvariable %} steps.secret_id_generator.outputs.SECRET_KEY {% templatetag closevariable %}
          DATABASE_URL: "sqlite:///"
          ALLOWED_HOSTS: ".example.org"
          SENDGRID_USERNAME: "test"
          SENDGRID_PASSWORD: "test"
          REDIS_URL: "redis://"
        shell: bash

      - name: Run tests with coverage
        run: |
          poetry run coverage run manage.py test
          mkdir -p junit
          poetry run coverage xml -o junit/test-results.xml
        shell: bash
